version: '3.6'
services:
  postgres:
    image: postgres:10
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgrespassword

  graphql-engine:
    image: hasura/graphql-engine:v2.3.0
    ports:
      - "3011:8080"
      # - "3000:3000"
    depends_on:
      - postgres
    restart: always
    environment:
      # 用于存储 Hasura 元数据的 Postgres 数据库 URL
      HASURA_GRAPHQL_METADATA_DATABASE_URL: "postgres://postgres:postgrespassword@postgres:5432/postgres"
      HASURA_GRAPHQL_DATABASE_URL: 
      # 可将上面的 Postgres 数据库作为数据源添加到 Hasura 中，根据需要可修改或删除此项
      PG_DATABASE_URL: 
      # 启用控制台，设置为 "false" 可禁用
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
      # 开发模式，建议生产环境关闭
      HASURA_GRAPHQL_DEV_MODE: "true"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "startup,http-log,webhook-log,websocket-log,query-log"
      # 设置未授权角色
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "anonymous"
      # 设置管理员密码
      HASURA_GRAPHQL_ADMIN_SECRET: "postgres"
      # 仅启用 graphql 和 metadata API
      HASURA_GRAPHQL_ENABLED_APIS: "graphql,metadata"
      HASURA_GRAPHQL_LOG_LEVEL: "debug"
      # 设置 Actions Handler 的 webhook URL（如有需要，可取消注释使用）
      # HASURA_GRAPHQL_ACTIONS_HANDLER_WEBHOOK_BASEURL: "http://cosmosexplorer.treasurenet.io:3012"
      HASURA_GRAPHQL_ACTIONS_HANDLER_WEBHOOK_BASEURL: 

volumes:
  db_data:
